config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do
    resources :user_surveys, :controller => "user_surveys" do
      resources :questions, :controller => "user_surveys/questions" do
        resources :options, :controller => "user_surveys/questions/options"
      end
    end
  end
  get 'survey', to: "user_survey#show"
end

app/models/spree/user_decorator.rb
if Spree.user_class
  Spree.user_class.class_eval do
    attr_accessible :survey_complete, :user_survey_id

    belongs_to :user_survey, :class_name => "Spree::UserSurvey"    
    has_many :user_survey_answer, :class_name => "Spree::UserSurveyAnswer", :dependent => :destroy

    def survey_complete?
      :survey_complete
    end

  end
end

app/models/spree/user_survey.rb
module Spree
  class UserSurvey < ActiveRecord::Base
    attr_accessible :title
    
    #validates :user, :presence => true
    if Spree.user_class
      has_many :user, :class_name => Spree.user_class.to_s
    else
      has_many :user
    end

    has_many :user_survey_question, :class_name => "Spree::UserSurveyQuestion"
  end
end

app/models/spree/user_survey_answer.rb
module Spree
  class UserSurveyAnswer < ActiveRecord::Base
    attr_accessible :user_survey_question, :options, :question

    validates :user, :presence => true
    if Spree.user_class
      belongs_to :user, :class_name => Spree.user_class.to_s
    else
      belongs_to :user
    end
    belongs_to :user_survey_question, :class_name => "Spree::UserSurveyQuestion"

    has_many :options, :class_name => "Spree::UserSurveyAnswerOption", :dependent => :destroy

    accepts_nested_attributes_for :options

    def option_attributes=(option_attributes)
      # Process the attributes hash
      option_attributes.each do |attributes|
        options.build(attributes)
      end
    end 
  end
end

app/models/spree/user_survey_answer_option.rb
module Spree
  class UserSurveyAnswerOption < ActiveRecord::Base
    attr_accessible :user_survey_answer, :checked, :answer
    belongs_to :user_survey_answer, :class_name => "Spree::UserSurveyAnswer"
  end
end

app/models/spree/user_survey_question.rb
module Spree
  class UserSurveyQuestion < ActiveRecord::Base
    attr_accessible :user_survey, :question, :options
    belongs_to :user_survey, :class_name => "Spree::UserSurvey"
    belongs_to :question_type, :class_name => "Spree::UserSurveyQuestionType"
    has_many :options, :class_name => "Spree::UserSurveyQuestionOption", :dependent => :destroy
    has_many :answers, :class_name => "Spree::UserSurveyQuestionAnswer"    
  end
end

app/models/spree/user_survey_question_option.rb
module Spree
  class UserSurveyQuestionOption < ActiveRecord::Base
    attr_accessible :user_survey_question, :option
    belongs_to :user_survey_question, :class_name => "Spree::UserSurveyQuestion"
  end
end

app/models/spree/user_survey_question_type.rb
module Spree
  class UserSurveyQuestionType < ActiveRecord::Base 
    attr_accessible :type_name
  end
end

app/controllers/spree/admin/user_surveys/questions/options_controller.rb
module Spree
  module Admin
    module UserSurveys
      module Questions
        class OptionsController < Spree::Admin::BaseController
         
          def show
            redirect_to( :action => 'edit' )
          end
          
        end
      end
    end
  end
end

app/controllers/spree/admin/user_surveys/questions_controller.rb
module Spree
  module Admin
    module UserSurveys
      class QuestionsController < Spree::Admin::BaseController
        before_filter :load_user_survey
        before_filter :load_user_survey_question, :only => [:show, :edit, :update, :ship]
        before_filter :load_user_survey_question_options, :only => [:edit]
        
        def show
          redirect_to( :action => :edit )
        end
        
        def index
          @questions = UserSurveyQuestion.where(:user_survey_id => @survey.id)
        end
        
        def new
          @question = @survey.user_survey_question.build 
        end

        def create
          if (new_question = @survey.user_survey_question.create(params[:user_survey_question]))
            flash[:notice] = t('question_created')
            redirect_to admin_user_survey_question_path(@survey, new_question)
          else
            flash[:error] = t(:question_not_created)
            render :new
          end
        end

        def update
          if @question.update_attributes(params[:user_survey_question])
            flash[:notice] = t('question_updated')
            redirect_to admin_magazine_issue_path(@survey, @question)
          else
            flash[:error] = t(:question_not_updated)
            render :action => :edit
          end 
        end

        private

        def load_user_survey
          @survey = UserSurvey.find_by_id(params[:user_survey_id])
        end

        def load_user_survey_question
          @question = UserSurveyQuestion.find(params[:id])
        end
        
        def load_user_survey_question_options
          @question_options = UserSurveyQuestionOption.where(:user_survey_question_id => @question.id)
        end
      end
    end
  end
end

app/controllers/spree/admin/user_surveys_controller.rb
module Spree
  module Admin
    class UserSurveysController < ResourceController
      before_filter :load_questions, :only => [:show, :edit]

      def show
        redirect_to( :action => :edit )
      end

      def index
        params[:q] ||= {}
        @search = UserSurvey.search(params[:q])
        @user_survey = @search.result.page(params[:page]).per(15)
      end

      def create
        create_or_update t("user_survey_successfully_created")
      end

      def update
        create_or_update t("user_survey_successfully_updated")
      end

      protected

      def load_questions
        @questions = UserSurveyQuestion.where(:user_survey_id => @user_survey.id)
      end
      
      private

      def create_or_update(flash_msg)
        if @user_survey.update_attributes(params[:user_survey])
          redirect_to edit_admin_user_survey_path(@user_survey)
          flash.notice = flash_msg
        else
          respond_with(@user_survey)
        end
      end

    end
  end
end

app/controllers/spree/user_sessions_controller_decorator.rb
Spree::UserSessionsController.class_eval do
  
  private
  
  def after_sign_in_path_for(resource_or_scope)
    
    user = spree_current_user
    if user != nil and !user.survey_complete?
      redirect survey_path
    else
      stored_location_for(resource_or_scope) || signed_in_root_path(resource_or_scope)
    end
  end
end

app/controllers/spree/user_survey_controller.rb
module Spree
  class UserSurveyController < Spree::StoreController
    before_filter :load_user
    before_filter :check_user_survey_exist
    
    rescue_from ActiveRecord::RecordNotFound, :with => :render_404
    respond_to :html

    def show
      survey = UserSurvey.find(@user.user_survey_id)
      if survey == nil
        redirect_to home_path
      end
      questions = UserSurveyQuestion.where(:user_survey_id => survey.id)
      @answers = Array.new
      questions.each do |question| 
        answer = UserSurveyAnswer.new(user_survey_question: question, question: question.question)
        
        #options = Array.new
        question.options.each do |question_option|
          answer.options.build(user_survey_answer: answer, answer:question_option.option)
          #UserSurveyAnswerOption.build
          #(user_survey_answer: answer, answer:question_option.option)
          #options.push(option)
        end

        #answer.options = options
        @answers.push(answer)
      end
    end

    def create
    
    end

    private

    def load_user
      @user = spree_current_user
      if @user == nil 
        redirect_to root_path
      end
    end
    
    def check_user_survey_exist
      if @user.survey_complete? == true
        redirect_to root_path  
      end
    end

    def create_user_answer(question)
      
    end
  end
end

app/views/spree/admin/user_surveys/_form.html.erb
<%= f.field_container :user_survey do %>
  <%= f.label :title, t(:title, :scope => 'activerecord.attributes.spree/user_survey') %><br />
  <%= f.text_field :title %>
  <%= f.error_message_on :title %>
<% end %>

app/views/spree/admin/user_surveys/edit.html.erb
<%= csrf_meta_tags %>

<div data-hook="admin_user_survey_edit_header">
  <h2>Editing User Survey</h2>
  <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @user_survey } %>
</div>

<div data-hook="admin_user_survey_edit_form">
  <div id="user_survey-form-wrapper">
    <%= form_for [:admin, @user_survey] do |f| %>
      <%= render :partial => 'form', :locals => { :f => f } %>
      <p class="form-buttons">
        <%= button "update title" %>
      </p>
    <% end %>
  </div>
</div>

</br>

<table>
  <thead>
    <tr>
      <th><%= t(:created_at, :scope => 'activerecord.attributes.spree/user_survey_question') %></th>
      <th><%= t(:id, :scope => 'activerecord.attributes.spree/user_survey_question') %></th>
      <th><%= t(:question_type, :scope => 'activerecord.attributes.spree/user_survey_question') %></th>
      <th><%= t(:question, :scope => 'activerecord.attributes.spree/user_survey_question') %></th>
      <th data-hook="admin_user_survey_index_header_actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.created_at.to_date %></td>
        <td><%= link_to question.id, admin_user_survey_question_url(@user_survey, question)%></td>
        <td><%= question.question_type %></td>
        <td><%= question.question %> </td>
        <td class="actions" data-hook="admin_user_survey_question_row_actions">
          <%= link_to_edit question, :class => 'edit' %>
          &nbsp;
          <%= link_to_delete question  %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/user_surveys/index.html.erb
<% content_for :page_title do %>
  <%= t(:listing_user_surveys) %>
<% end %>

<% content_for :page_actions do %>
  <li id="new_user_survey_link">
    <%= button_link_to t(:new_user_survey), new_object_url, { :icon => 'icon-plus', :id => 'admin_new_user_survey' } %>
  </li>
<% end %>

<table>
  <thead>
    <tr>
      <th><%= sort_link @search, :created_at, t(:created_at, :scope => 'activerecord.attributes.spree/user_survey')%></th>
      <th><%= sort_link @search, :id, t(:id, :scope => 'activerecord.attributes.spree/user_survey')%></th>
      <th><%= sort_link @search, :title, t(:title, :scope => 'activerecord.attributes.spree/user_survey')%></th>
      <th data-hook="admin_user_survey_index_header_actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @user_survey.each do |survey| %>
      <tr>
        <td><%= survey.created_at.to_date %></td>
        <td><%= link_to survey.id, edit_object_url(survey) %></td>
        <td><%= survey.title %></td>
        <td class="actions" data-hook="admin_user_survey_index_row_actions">
          <%= link_to_edit survey, :class => 'edit' %>
          &nbsp;
          <%= link_to_delete survey %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @user_survey %>

app/views/spree/admin/user_surveys/new.html.erb
<%= csrf_meta_tags %>

<div data-hook="admin_user_survey_new_header">
  <h2>Creating User Survey</h2>
  <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @user_survey } %>
</div>

<div data-hook="admin_user_survey_new_form">
  <div id="user_survey-form-wrapper">
    <%= form_for [:admin, @user_survey] do |f| %>
      <%= render :partial => 'form', :locals => { :f => f } %>
      <p class="form-buttons">
        <%= button "create" %> <%= link_to "cancel", collection_url %>
      </p>
    <% end %>
  </div>
</div>

app/views/spree/admin/user_surveys/questions/_form.html.erb
<%= f.field_container :question do %>
  <%= f.label :question, t(:question, :scope => 'activerecord.attributes.spree/user_survey_question') %>
  <%= f.text_field :question %>
  <%= f.error_message_on :question %>
<% end %>

app/views/spree/admin/user_surveys/questions/edit.html.erb
<%= csrf_meta_tags %>

<div data-hook="admin_user_survey_question_new_header">
  <h2><%= t('Editing User Survey Question')%></h2>
  <%= render :partial => 'spree/shared/error_messages', :locals => {:target => @question } %>
</div>

<div data-hook="admin_user_survey_question_edit_form">
  <div id="user_survey_question-form-wrapper">
    <%= form_for [:admin, @question] do |f| %>
      <%= render :partial => 'form', :locals => { :f => f } %>
      <p class="form-buttons">
      <%= button "update question" %>
      </p>
    <% end %>
  </div>
</div>

</br>

<%= render :partial => 'spree/admin/user_surveys/questions/options/table', :locals => { :survey => @survey, :question => @question, :options => @question_options } %> 

app/views/spree/admin/user_surveys/questions/index.html.erb
<% content_for :page_title do %>
  <%= t(:listing_questions_for_survey)  %>
  <%= @survey.id %>
<% end %>

<table> 
  <thead>
    <tr>
      <th><%= t(:created_at, :scope => 'activerecord.attributes.spree/user_survey_question') %></th>
      <th><%= t(:id, :scope => 'activerecord.attributes.spree/user_survey_question') %></th>
      <th><%= t(:question_type, :scope => 'activerecord.attributes.spree/user_survey_question') %></th>
      <th><%= t(:question, :scope => 'activerecord.attributes.spree/user_survey_question') %></th>
      <th data-hook="admin_user_survey_index_header_actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.created_at.to_date %></td>
        <td><%= link_to question.id, admin_user_survey_question_url(@survey,question) %></td>
        <td><%= question.question_type %></td>
        <td><%= question.question %> </td>
        <td class="actions" data-hook="admin_user_survey_question_index_row_actions">
          <%= link_to_edit_url edit_admin_user_survey_question_path(@survey,question) %>
          &nbsp;
          <%= link_to_delete question, :url => admin_user_survey_question_path(@survey,question) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/user_surveys/questions/options/_table.html.erb
<table>
  <thead>
    <th><%= t(:created_at, :scope => 'activerecord.attributes.spree/user_survey_question_option') %></th>
    <th><%= t(:id, :scope => 'activerecord.attributes.spree/user_survey_question_option') %></th>
    <th><%= t(:option_name, :scope => 'activerecord.attributes.spree/user_survey_question_option') %></th>
    <th data-hook="admin_user_survey_question_option_header_actions"></th>
  </thead>
  <tbody>
    <% if options %>
    <% options.each do |option| %>  
      <tr>
        <td><%= option.created_at.to_date %></td>
        <td><%= link_to option.id, admin_user_survey_question_option_url(survey,question,option) %></td>
        <td><%= option.option_name %></td>
        <td class="actions" data-hook="admin_user_survey_quesiton_option_row_actions">
          

        </td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

app/views/spree/user_survey/show.html.erb
<h1><%= t(:survey) %></h1>

<% @answers.each do |answer| %>
  <div>
    <%= form_for answer, :url => 'survey#create' do |f| %>
      <h2><%= answer.question %></h2></br>
    <% for option in answer.options %>
      <%= fields_for "answer[option_attributes][]", option do |option_form|%>
        <p>
        <%= option.answer %>
        <%= option_form.check_box :checked  %>
        </p>
      <% end %>  
    <% end %>
    <%= f.submit %>
  <% end %>
  </div>
<%end %>